source 'https://rubygems.org' do
  gem 'sinatra'
  gem 'test-unit', require: 'test/unit'
  gem 'rack-test', require: 'rack/test'
  gem 'faker'
  gem 'sqlite3'
  gem 'activerecord'
  gem 'puma'
  gem 'rabl'
  gem 'builder'
end
